eureka:
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

# JWT TOKEN SECRET
jwt:
  secret:
      key: EIc8UvBDiglAeF7QxFaPdZhrdPqI+6athOt4DmU7XI4=
